### ISSUE TITLE
Latest Docker image crashes on arm32v7

### ISSUE THREAD

**Issue by LouisMT** [xirixiz/dsmr-reader-docker#203]
## Setup/Architecture information
Docker on arm32v7.

## Version of the Docker image
latest-2021.04.02-arm32v7

## Configuration
```yaml
dsmr:
  image: xirixiz/dsmr-reader-docker:latest-2021.04.02-arm32v7
  restart: always
  volumes:
    - /etc/localtime:/etc/localtime:ro
  environment:
    - DJANGO_DATABASE_HOST=dsmr-postgres
    - DJANGO_TIME_ZONE=Europe/Amsterdam
    - DSMRREADER_ADMIN_USER=[redacted]
    - DSMRREADER_ADMIN_PASSWORD=[redacted]
    - VIRTUAL_HOST=[redacted]
  depends_on:
    - dsmr-postgres
  networks:
    - main
```

## Describe the bug
The container won't start and keeps crashing. Simply setting the version to `latest-2021.04.01-arm32v7` (the previous version) resolves the problem.

## Debug log

```text
[ INFO ] DSMR release: v4.15.1
[ INFO ] Removing existing PID files...
[ INFO ] Creating log directory...
[ INFO ] Fixing /dev/ttyUSB* security...
[ INFO ] Verifying if the DSMR web credential variables have been set...
[ INFO ] Verifying database connectivity to host: dsmr-postgres with port: 5432...
[ INFO ] Database connectivity successfully verified!
[ INFO ] Running post configuration...
dsmr_1           | Fatal Python error: init_interp_main: can't initialize time
dsmr_1           | Python runtime state: core initialized
dsmr_1           | PermissionError: [Errno 1] Operation not permitted
dsmr_1           | 
dsmr_1           | Current thread 0xb6f1b390 (most recent call first):
dsmr_1           | <no Python frame>
dsmr_1           | Fatal Python error: init_interp_main: can't initialize time
dsmr_1           | Python runtime state: core initialized
dsmr_1           | PermissionError: [Errno 1] Operation not permitted
dsmr_1           | 
dsmr_1           | Current thread 0xb6fe7390 (most recent call first):
dsmr_1           | <no Python frame>
dsmr_1           | Fatal Python error: init_interp_main: can't initialize time
dsmr_1           | Python runtime state: core initialized
dsmr_1           | PermissionError: [Errno 1] Operation not permitted
dsmr_1           | 
dsmr_1           | Current thread 0xb6f3b390 (most recent call first):
dsmr_1           | <no Python frame>
[ INFO ] Checking for NGINX SSL configuration...
[ INFO ] ENABLE_NGINX_SSL is disabled, nothing to see here. Continuing...
[ INFO ] Checking for HTTP AUTHENTICATION configuration...
[ INFO ] ENABLE_HTTP_AUTH is disabled, nothing to see here. Continuing...
[ INFO ] Configuring DSMR in standlone datalogger mode....
[ INFO ] Starting supervisord...
[ INFO ] Logfiles can be found at: /var/log/supervisor/*.log and /tmp/supervisord.log
dsmr_1           | Fatal Python error: pyinit_main: can't initialize time
dsmr_1           | Python runtime state: core initialized
dsmr_1           | PermissionError: [Errno 1] Operation not permitted
dsmr_1           | 
dsmr_1           | Current thread 0xb6f65390 (most recent call first):
dsmr_1           | <no Python frame>
[ INFO ] DSMR release: v4.15.1
[ INFO ] Removing existing PID files...
[ INFO ] Creating log directory...
[ INFO ] Fixing /dev/ttyUSB* security...
[ INFO ] Verifying if the DSMR web credential variables have been set...
[ INFO ] Verifying database connectivity to host: dsmr-postgres with port: 5432...
dsmr_1           | nc: getaddrinfo: Try again
dsmr_1           | nc: getaddrinfo: Try again
dsmr_1           | nc: getaddrinfo: Try again
[ INFO ] Database connectivity successfully verified!nds...
[ INFO ] Running post configuration...
dsmr_1           | Fatal Python error: init_interp_main: can't initialize time
dsmr_1           | Python runtime state: core initialized
dsmr_1           | PermissionError: [Errno 1] Operation not permitted
dsmr_1           | 
dsmr_1           | Current thread 0xb6f6c390 (most recent call first):
dsmr_1           | <no Python frame>
dsmr_1           | Fatal Python error: init_interp_main: can't initialize time
dsmr_1           | Python runtime state: core initialized
dsmr_1           | PermissionError: [Errno 1] Operation not permitted
dsmr_1           | 
dsmr_1           | Current thread 0xb6f24390 (most recent call first):
dsmr_1           | <no Python frame>
dsmr_1           | Fatal Python error: init_interp_main: can't initialize time
dsmr_1           | Python runtime state: core initialized
dsmr_1           | PermissionError: [Errno 1] Operation not permitted
dsmr_1           | 
dsmr_1           | Current thread 0xb6f5c390 (most recent call first):
dsmr_1           | <no Python frame>
[ INFO ] Checking for NGINX SSL configuration...
[ INFO ] ENABLE_NGINX_SSL is disabled, nothing to see here. Continuing...
[ INFO ] Checking for HTTP AUTHENTICATION configuration...
[ INFO ] ENABLE_HTTP_AUTH is disabled, nothing to see here. Continuing...
[ INFO ] Configuring DSMR in standlone datalogger mode....
[ INFO ] Starting supervisord...
[ INFO ] Logfiles can be found at: /var/log/supervisor/*.log and /tmp/supervisord.log
dsmr_1           | Fatal Python error: pyinit_main: can't initialize time
dsmr_1           | Python runtime state: core initialized
dsmr_1           | PermissionError: [Errno 1] Operation not permitted
dsmr_1           | 
dsmr_1           | Current thread 0xb6fb6390 (most recent call first):
dsmr_1           | <no Python frame>
[ INFO ] DSMR release: v4.15.1
[ INFO ] Removing existing PID files...
[ INFO ] Creating log directory...
[ INFO ] Fixing /dev/ttyUSB* security...
[ INFO ] Verifying if the DSMR web credential variables have been set...
[ INFO ] Verifying database connectivity to host: dsmr-postgres with port: 5432...
dsmr_1           | nc: getaddrinfo: Try again
dsmr_1           | nc: getaddrinfo: Try again
dsmr_1           | nc: getaddrinfo: Try again
dsmr_1           | nc: getaddrinfo: Try again
dsmr_1           | nc: getaddrinfo: Try again
dsmr_1           | nc: getaddrinfo: Try again
dsmr_1           | nc: getaddrinfo: Try again
dsmr_1           | nc: getaddrinfo: Try again
dsmr_1           | nc: getaddrinfo: Try again
dsmr_1           | nc: getaddrinfo: Try again
dsmr_1           | nc: getaddrinfo: Try again
dsmr_1           | nc: getaddrinfo: Try again
dsmr_1           | nc: getaddrinfo: Try again
dsmr_1           | nc: getaddrinfo: Try again
dsmr_1           | nc: getaddrinfo: Try again
dsmr_1           | nc: getaddrinfo: Try again
dsmr_1           | nc: getaddrinfo: Try again
dsmr_1           | nc: getaddrinfo: Try again
dsmr_1           | nc: getaddrinfo: Try again
dsmr_1           | nc: getaddrinfo: Try again
dsmr_1           | nc: getaddrinfo: Try again
dsmr_1           | nc: getaddrinfo: Try again
dsmr_1           | nc: getaddrinfo: Try again
[ INFO ] Database connectivity successfully verified!onds...
[ INFO ] Running post configuration...
dsmr_1           | Fatal Python error: init_interp_main: can't initialize time
dsmr_1           | Python runtime state: core initialized
dsmr_1           | PermissionError: [Errno 1] Operation not permitted
dsmr_1           | 
dsmr_1           | Current thread 0xb6fb8390 (most recent call first):
dsmr_1           | <no Python frame>
dsmr_1           | Fatal Python error: init_interp_main: can't initialize time
dsmr_1           | Python runtime state: core initialized
dsmr_1           | PermissionError: [Errno 1] Operation not permitted
dsmr_1           | 
dsmr_1           | Current thread 0xb6fba390 (most recent call first):
dsmr_1           | <no Python frame>
dsmr_1           | Fatal Python error: init_interp_main: can't initialize time
dsmr_1           | Python runtime state: core initialized
dsmr_1           | PermissionError: [Errno 1] Operation not permitted
dsmr_1           | 
dsmr_1           | Current thread 0xb6fe8390 (most recent call first):
dsmr_1           | <no Python frame>
[ INFO ] Checking for NGINX SSL configuration...
[ INFO ] ENABLE_NGINX_SSL is disabled, nothing to see here. Continuing...
[ INFO ] Checking for HTTP AUTHENTICATION configuration...
[ INFO ] ENABLE_HTTP_AUTH is disabled, nothing to see here. Continuing...
[ INFO ] Configuring DSMR in standlone datalogger mode....
[ INFO ] Starting supervisord...
[ INFO ] Logfiles can be found at: /var/log/supervisor/*.log and /tmp/supervisord.log
dsmr_1           | Fatal Python error: pyinit_main: can't initialize time
dsmr_1           | Python runtime state: core initialized
dsmr_1           | PermissionError: [Errno 1] Operation not permitted
dsmr_1           | 
dsmr_1           | Current thread 0xb6f0d390 (most recent call first):
dsmr_1           | <no Python frame>
```

**Comment by xirixiz** [comment]
Hi, I think I've found a solution. Building ```xirixiz/dsmr-reader-docker:development-2021.04.03-arm32v7```.

Please try this image in about 30 minutes.... or later 😄

**Comment by xirixiz** [comment]
If not, you could try this: https://github.com/timothymiller/cloudflare-ddns/issues/46

**Comment by LouisMT** [comment]
Hey, I tried `xirixiz/dsmr-reader-docker:development-2021.04.03-arm32v7`, unfortunately that doesn't work.

Using `privileged: true` does work.

Do you have any idea what may be causing this issue? I don't have it on my amd64 machine. And I prefer not to use `privileged`! :)

**Comment by LouisMT** [comment]
Okay, so this is caused by the upgrade from Alpine 3.12 to 3.13.

Alpine 3.13 requires the following (https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements):
* Docker 19.03.9 or newer
* libseccomp 2.4.2 or newer

The `libseccomp` package hasn't been updated for Debian stable yet, Therefore, this image won't run on any Debian (or Raspbian) stable host.

I just upgraded the `libseccomp` package manually (thanks to https://github.com/alpinelinux/docker-alpine/issues/135#issuecomment-812287338) and it's working great now! But another solution is to wait until Debian updates the package for stable:

```
wget https://ftp.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
sudo dpkg -i libseccomp2_2.5.1-1_armhf.deb
rm libseccomp2_2.5.1-1_armhf.deb
```

**Comment by Nenodema** [comment]
Any idea when a permanent fix is available for this?

**Comment by xirixiz** [comment]
Better wait indeed :). No other issues announced here and it's more related to the host.

**Comment by EYEVO** [comment]
Same here on a R pi 3b. Any fix on this?

**Comment by LouisMT** [comment]
It seems the best solution right now is to install `libseccomp2` from the official Debian Buster backports repository.

**Comment by xirixiz** [comment]
Yes, it is. But since this issue is still occuring I might add it to the next release.

**Comment by xirixiz** [comment]
Release 2021.05.05 should fix this. Please verify once the Docker image is available.

**Comment by wtreur** [comment]
Release 2021.05.05 doesn't fix the issue (#207), since `libseccomp2` needs to be installed on the host machine and not inside the container. I guess the only option for now is to add some instructions in the readme/install notes.

**Comment by Paraphraser** [comment]
The fix is described [here](https://blog.samcater.com/fix-workaround-rpi4-docker-libseccomp2-docker-20/):

```
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
$ echo 'deb http://httpredir.debian.org/debian buster-backports main contrib non-free' | sudo tee -a /etc/apt/sources.list.d/debian-backports.list
$ sudo apt update
$ sudo apt install libseccomp2 -t buster-backports
```

I've installed it on RPi4 and RPi3B+.
